config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'mainpage#index'

  get 'hospitals/search', to: 'hospitals#search', as: 'hospitals_search'
  get 'hospitals/download_csv', to: 'hospitals#download_csv', as: 'hospitals_download_csv'
  get 'hospitals/download_pdf', to: 'hospitals#download_pdf', as: 'hospitals_download_pdf'
  get 'hospitals/:id/download_pdf/', to: 'hospitals#download_pdf_with_id', as: 'hospitals_download_pdf_with_id'
  get 'users/download_pdf/', to: 'mainpage#download_pdf', as: 'users_download_pdf'
  get 'hospitals/:id/searchshow', to: 'hospitals#searchshow', as: 'hospitals_search_show'
  get 'departments/search', to: 'departments#search', as: 'departments_search'
  get 'doctors/search', to: 'doctors#search', as: 'doctors_search'
  get 'specialties/search', to: 'specialties#search', as: 'specialties_search'
  get 'patient_cards/search', to: 'patient_cards#search', as: 'patient_cards_search'
  get 'patients/search', to: 'patients#search', as: 'patients_search'

  root 'mainpage#index'

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :hospitals do
    resources :departments
  end

  resources :departments do
    resources :doctors
  end

  resources :departments do
    resources :patient_cards
  end

  resources :patient_cards

  resources :patients

  resources :doctors do
    resources :specialties
  end

  resources :specialties
end

app/models/patient.rb
class Patient < ApplicationRecord
	has_one :patient_card, dependent: :destroy

	validates :name, presence: true, length: { maximum: 50 }
	validates :birthdate, presence: true, format: { with: /\A\d{4}-\d{2}-\d{2}\z/, message: "Invalid date format! Example: 'YYYY-MM-DD'" }
	validates :phone, presence: true, length: { maximum: 20 }, format: { with: /\A\+?\d+\z/, message: "Invalid phone format!" }
	validates :address, presence: true, length: { maximum: 100 }

	def update_name(new_name)
		self.name = new_name
		save
	end

	def update_birthdate(new_birthdate)
		self.birthdate = new_birthdate
		save
	end

	def update_phone(new_phone)
		self.phone = new_phone
		save
	end

	def update_address(new_address)
		self.address = new_address
		save
	end

	def age
    	now = Time.now.utc.to_date
    	now.year - birthdate.year - (birthdate.to_date.change(year: now.year) > now ? 1 : 0)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @patients = PatientQuery.new(Patient.page(params[:page]).per(10))
    @patients = @patients.sort(params[:sort], params[:direction]) if params[:sort].present?
    @patients = @patients.search(:name, params[:name]) if params[:name].present?
    @patients = @patients.result
  end
  
  def search
    @patients = PatientQuery.new(Patient.page(params[:page]).per(10))
    @patients = @patients.sort(params[:sort], params[:direction]) if params[:sort].present?
    @patients = @patients.search(:name, params[:name]) if params[:name].present?
    @patients = @patients.result

    render :index
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)

    begin
      if @patient.save
        redirect_to patient_path(@patient)
      else
        render :new
      end
    rescue ActiveRecord::RecordNotUnique => e
      flash[:error] = "An error occurred: #{e.message}"
      render :new
    end
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])

    begin
      if @patient.update(patient_params)
        redirect_to patient_path(@patient)
      else
        render :edit
      end
    rescue ActiveRecord::RecordNotUnique => e
      flash[:error] = "An error occurred: #{e.message}"
      render :edit
    end
  end

  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy
    redirect_to patients_path
  end

  private

  def patient_params
    params.require(:patient).permit(:name, :birthdate, :phone, :address)
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/edit.html.erb
<%= stylesheet_link_tag 'form' %>

<h1> Update Patient </h1>

<%= form_for @patient do |f| %>
  <%= f.label :name, class: "label" %>
  <%= f.text_field :name, class: "input-field", placeholder: "Test Testov Testovich" %><br>

  <%= f.label :birthdate, class: "label" %>
  <%= f.text_field :birthdate, class: "input-field", placeholder: "2023-03-23" %><br>

  <%= f.label :phone, class: "label" %>
  <%= f.text_field :phone, class: "input-field", placeholder: "+3801234567" %><br>

  <%= f.label :address, class: "label" %>
  <%= f.text_field :address, class: "input-field", placeholder: "123 Adr Street" %><br>

  <%= f.submit "Update", class: "button" %>

  <div id="error-message" class="large-label"></div>
<% end %>

app/views/patients/index.html.erb
<%= stylesheet_link_tag 'view' %>

<h1>View patients</h1>

<table>
  <thead>
    <tr>
      <th style="width: 55px;">
        <%= label_tag "id", "ID" %>
        <%= link_to params[:sort] == "id" && params[:direction] == "asc" ? "▼" : "▲", { sort: "id", direction: params[:sort] == "id" && params[:direction] == "asc" ? "desc" : "asc", id: params[:id] }, class: "sort-icon #{params[:sort] == "id" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
      </th>
      <th style="width: 220px;">
        <%= form_tag(patients_search_path, method: "get") do %>
          <%= label_tag "name", "Name" %>
          <%= text_field_tag "name", params[:name], placeholder: "Search...", size: 4 %>
          <%= submit_tag "Search", class: "small-button" %>
          <%= link_to params[:sort] == "name" && params[:direction] == "asc" ? "▼" : "▲", { sort: "name", direction: params[:sort] == "name" && params[:direction] == "asc" ? "desc" : "asc", name: params[:name] }, class: "sort-icon #{params[:sort] == "name" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
        <% end %>
      </th>
      <th style="width: 115px">
        <%= label_tag "birthdate", "Birthdate" %>
        <%= link_to params[:sort] == "birthdate" && params[:direction] == "asc" ? "▼" : "▲", { sort: "birthdate", direction: params[:sort] == "birthdate" && params[:direction] == "asc" ? "desc" : "asc", birthdate: params[:birthdate] }, class: "sort-icon #{params[:sort] == "birthdate" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
      </th>
      <th style="width: 135px">
        <%= label_tag "phone", "Phone" %>
        <%= link_to params[:sort] == "phone" && params[:direction] == "asc" ? "▼" : "▲", { sort: "phone", direction: params[:sort] == "phone" && params[:direction] == "asc" ? "desc" : "asc", phone: params[:phone] }, class: "sort-icon #{params[:sort] == "phone" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
      </th>
      <th style="min-width: 160px; width: auto;">
        <%= label_tag "address", "Address" %>
        <%= link_to params[:sort] == "address" && params[:direction] == "asc" ? "▼" : "▲", { sort: "address", direction: params[:sort] == "address" && params[:direction] == "asc" ? "desc" : "asc", address: params[:address] }, class: "sort-icon #{params[:sort] == "" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
      </th>
      <th colspan="3" style="width: 270px;">Data interraction</th>
    </tr>
  </thead>
  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.id %></td>
        <td><%= patient.name %></td>
        <td><%= patient.birthdate %></td>
        <td><%= patient.phone %></td>
        <td><%= patient.address %></td>
        <td><%= link_to 'Show', patient_path(patient), class: "button" %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient), class: "button" %></td>
        <td><%= button_to 'Delete', patient_path(patient), method: :delete, data: { confirm: 'Are you sure?' }, class: "button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @patients %>

<div class="links-container">
  <%= link_to 'New Patient', new_patient_path, class: "bottom-button" %>
  <%= link_to 'Main page', '/', class: "bottom-button" %>
</div>

app/views/patients/new.html.erb
<%= stylesheet_link_tag 'form' %>

<h1> Add Patient </h1>

<%= form_for @patient do |f| %>
  <%= f.label :name, class: "label" %>
  <%= f.text_field :name, class: "input-field", placeholder: "Test Testov Testovich" %><br>

  <%= f.label :birthdate, class: "label" %>
  <%= f.text_field :birthdate, class: "input-field", placeholder: "2023-03-23" %><br>

  <%= f.label :phone, class: "label" %>
  <%= f.text_field :phone, class: "input-field", placeholder: "+3801234567" %><br>

  <%= f.label :address, class: "label" %>
  <%= f.text_field :address, class: "input-field", placeholder: "123 Adr Street" %><br>

  <%= f.submit "Create", class: "button" %>

  <div id="error-message" class="large-label"></div>
<% end %>

app/views/patients/show.html.erb
<%= stylesheet_link_tag 'view' %>

<h1> View Some Patient </h1>

<table>
  <tr>
    <td> ID: </td>
    <td> <%= @patient.id %> </td>
  </tr>

  <tr>
    <td> Name: </td>
    <td> <%= @patient.name %> </td>
  </tr>

  <tr>
    <td> Birthdate: </td>
    <td> <%= @patient.birthdate %> </td>
  </tr>

  <tr>
    <td> Phone: </td>
    <td> <%= @patient.phone %> </td>
  </tr>

  <tr>
    <td> Address: </td>
    <td> <%= @patient.address %> </td>
  </tr>

</table>

<br>

<div class="links-container">
  <%= link_to 'Update', edit_patient_path(@patient), class: "bottom-button" %>
  <%= link_to 'Back to Patients', patients_path, class: "bottom-button" %>
  <%= link_to 'Back to Hospitals', hospitals_path, class: "bottom-button" %>
</div>