config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'mainpage#index'

  get 'hospitals/search', to: 'hospitals#search', as: 'hospitals_search'
  get 'hospitals/download_csv', to: 'hospitals#download_csv', as: 'hospitals_download_csv'
  get 'hospitals/download_pdf', to: 'hospitals#download_pdf', as: 'hospitals_download_pdf'
  get 'hospitals/:id/download_pdf/', to: 'hospitals#download_pdf_with_id', as: 'hospitals_download_pdf_with_id'
  get 'users/download_pdf/', to: 'mainpage#download_pdf', as: 'users_download_pdf'
  get 'hospitals/:id/searchshow', to: 'hospitals#searchshow', as: 'hospitals_search_show'
  get 'departments/search', to: 'departments#search', as: 'departments_search'
  get 'doctors/search', to: 'doctors#search', as: 'doctors_search'
  get 'specialties/search', to: 'specialties#search', as: 'specialties_search'
  get 'patient_cards/search', to: 'patient_cards#search', as: 'patient_cards_search'
  get 'patients/search', to: 'patients#search', as: 'patients_search'

  root 'mainpage#index'

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :hospitals do
    resources :departments
  end

  resources :departments do
    resources :doctors
  end

  resources :departments do
    resources :patient_cards
  end

  resources :patient_cards

  resources :patients

  resources :doctors do
    resources :specialties
  end

  resources :specialties
end

app/models/hospital.rb
class Hospital < ApplicationRecord
	has_many :departments, dependent: :destroy
	has_many :doctors, through: :departments
	has_many :patient_cards, dependent: :destroy
	has_many :patients, through: :patient_cards

	validates :name, presence: true, length: { maximum: 100 }
	validates :email, presence: true, length: { maximum: 255 }, format: { with: URI::MailTo::EMAIL_REGEXP, message: "Invalid email format!" }
	validates :phone, presence: true, length: { maximum: 20 }, format: { with: /\A\+?\d+\z/, message: "Invalid phone format!" }
	validates :address, presence: true, length: { maximum: 100 }
    validates :year, presence: true, length: { maximum: 10 }, format: { with: /\A(17[0-9]{2}|17[0-9]{2}|18[0-9]{2}|19[0-9]{2}|20[0-1][0-9]|202[0-3])\z/, message: "Incorrect year format!" }
	validates :facility, presence: true, length: { maximum: 100 }
	validates :city, presence: true, length: { maximum: 100 }
	validates :rating, presence: true, length: { maximum: 100 }
	def update_name(new_name)
		self.name = new_name
		save
	end

	def update_email(new_email)
		self.email = new_email
		save
	end

	def update_phone(new_phone)
		self.phone = new_phone
		save
	end

	def update_address(new_address)
		self.address = new_address
		save
	end

	def update_year(new_year)
		self.year = new_year
		save
	end

	def update_facility(new_facility)
		self.facility = new_facility
		save
	end

	def update_city(new_city)
		self.city = new_city
		save
	end

	def update_rating(new_rating)
		self.rating = new_rating
		save
	end
end

app/controllers/hospitals_controller.rb
require 'csv'
require 'prawn'
require 'prawn/table'
require 'thread'

class HospitalsController < ApplicationController
  def index
    hospitals = Hospital.all

    if params[:sort].present?
      hospitals = case params[:sort]
      when "id"
        hospitals.order!(id: params[:direction])
      when "departments_count"
        hospitals.left_outer_joins(:departments)
               .group(:id)
               .order!("COUNT(departments.id) #{params[:direction] == 'desc' ? 'DESC' : 'ASC'}")
      when "doctors_count"
        hospitals.left_outer_joins(:doctors)
               .group(:id)
               .order!("COUNT(doctors.id) #{params[:direction] == 'desc' ? 'DESC' : 'ASC'}")
      when "name"
        hospitals.order!(name: params[:direction])
      when "facility"
        hospitals.order!(facility: params[:direction])
      when "city"
        hospitals.order!(city: params[:direction])
      when "rating"
        hospitals.order!(rating: params[:direction])
      end
    end

    @hospitals = HospitalQuery.new(hospitals.page(params[:page]).per(10))
    @hospitals = @hospitals.search(:name, params[:name]) if params[:name].present?
    @hospitals = @hospitals.result
  end

  def search
    hospitals = Hospital.all

    if params[:sort].present?
      hospitals = case params[:sort]
      when "id"
        hospitals.order!(id: params[:direction])
      when "departments_count"
        hospitals.left_outer_joins(:departments)
               .group(:id)
               .order!("COUNT(departments.id) #{params[:direction] == 'desc' ? 'DESC' : 'ASC'}")
      when "doctors_count"
        hospitals.left_outer_joins(:doctors)
               .group(:id)
               .order!("COUNT(doctors.id) #{params[:direction] == 'desc' ? 'DESC' : 'ASC'}")
      when "name"
        hospitals.order!(name: params[:direction])
      when "facility"
        hospitals.order!(facility: params[:direction])
      when "city"
        hospitals.order!(city: params[:direction])
      when "rating"
        hospitals.order!(rating: params[:direction])
      end
    end

    @hospitals = HospitalQuery.new(hospitals.page(params[:page]).per(10))
    @hospitals = @hospitals.search(:name, params[:name]) if params[:name].present?
    @hospitals = @hospitals.result

    render :index
  end
  
  def show
    @hospital = Hospital.find(params[:id])
    patients = @hospital.patients.page(params[:page]).per(10)

    if params[:sort].present?
      patients = case params[:sort]
      when "id"
        patients.order(id: params[:direction])
      when "name"
        patients.order(name: params[:direction])
      when "birthdate"
        patients.order(birthdate: params[:direction])
      when "phone"
        patients.order(phone: params[:direction])
      else
        patients
      end
    end

    @patients = PatientQuery.new(patients)
    @patients = @patients.search(:name, params[:name]) if params[:name].present?
    @patients = @patients.search(:age, params[:age]) if params[:age].present?
    @patients = @patients.search(:phone, params[:phone]) if params[:phone].present?
    @patients = @patients.sort(params[:sort], params[:direction]) if params[:sort].present?
    @patients = @patients.result

    @patientcards = PatientCard.where(patient_id: @patients.map(&:id)).index_by(&:patient_id)
  end

  def searchshow
    @hospital = Hospital.find(params[:id])
    @patients = PatientQuery.new(@hospital.patients.page(params[:page]).per(10))
    @patients = @patients.search(:name, params[:name]) if params[:name].present?
    @patients = @patients.search(:age, params[:age]) if params[:age].present?
    @patients = @patients.search(:phone, params[:phone]) if params[:phone].present?
    @patients = @patients.sort(params[:sort], params[:direction]) if params[:sort].present?
    @patients = @patients.result

    @patientcards = PatientCard.where(hospital_id: @hospital.id, patient_id: @patients.pluck(:id)).index_by(&:patient_id)

    render :show
  end

  def download_csv
    mutex = Mutex.new
    threads = []
    filename = "hospitals_and_patients.csv"

    csv_headers = ["Hospital Name", "Hospital Email", "Hospital Phone", "Hospital Address", "Establishment Year", "Facility (Type)", "City", "Rating (Mortality)", "Department Count", "Doctor Count", "Patient Name", "Patient Phone", "Patient Address", "Patient Birthdate"]

    Tempfile.open(filename) do |tempfile|
      CSV.open(tempfile, "wb") do |csv|
        csv << csv_headers

        Hospital.includes(:patients).find_each do |hospital|
          hospital_data = [
            hospital.name,
            hospital.email,
            hospital.phone,
            hospital.address,
            hospital.year,
            hospital.facility,
            hospital.city,
            hospital.rating,
            hospital.departments.count,
            hospital.doctors.count
          ]
          csv << hospital_data

          hospital.patients.each_with_index do |patient, index|
            patient_data = [
              patient.name,
              patient.phone,
              patient.address,
              patient.birthdate
            ]
            csv << patient_data
          end
        end
      end

      threads << Thread.new do
        mutex.synchronize do
          send_file tempfile.path, filename: filename, type: "application/csv"
        end
      end

      threads.each(&:join)
    end
  end

  def download_pdf
    mutex = Mutex.new
    threads = []
    filename = "hospitals_and_patients.pdf"

    Tempfile.open(filename) do |tempfile|
      Prawn::Document.generate(tempfile.path) do |pdf|
        pdf.font_families.update("Georgia" => {
          normal: "#{Rails.root}/app/assets/fonts/NotoSansGeorgian-Regular.ttf",
          bold: "#{Rails.root}/app/assets/fonts/NotoSansGeorgian-Bold.ttf"
        })
        pdf.font "Georgia"

        hospitals = Hospital.includes(:patients)

        hospitals.each_with_index do |hospital, index|
          pdf.move_down(10)
          pdf.text "Hospital #{index + 1} Information", size: 14, style: :bold, align: :center

          hospital_data = [
            [{ content: 'Info', font_style: :bold }, { content: '', image: "#{Rails.root}/app/assets/images/hospital_info.png", fit: [20, 20] }],
            ["Hospital name", hospital.name],
            ["Email", hospital.email],
            ["Phone", hospital.phone],
            ["Address", hospital.address],
            ["Establishment Year", hospital.year],
            ["Type", hospital.facility],
            ["City", hospital.city],
            ["Mort. Rating", hospital.rating],
            ["Number of departments", hospital.departments.count],
            ["Number of doctors", hospital.doctors.count]
          ]

          pdf.table(hospital_data, width: 400, cell_style: { borders: [], padding: [4, 2] })

          if hospital.patients.any?
            pdf.move_down(10)
            pdf.text "Patients", size: 14, style: :bold, align: :center

            patient_headers = [
              { content: "Info", width: 43 },
              { content: "Name", width: 94 },
              { content: "Birth", width: 50 },
              { content: "Phone", width: 69 },
              { content: "Address", width: 119 },
              { content: "Code", width: 63 },
              { content: "Doctor", width: 107 }
            ]

            patient_data = hospital.patients.map do |patient|
              [
                { content: '', image: "#{Rails.root}/app/assets/images/patient_info.png", fit: [20, 20] },
                patient.name,
                patient.birthdate,
                patient.phone,
                patient.address,
                patient.patient_card&.code,
                patient.patient_card&.doctor&.name
              ]
            end

            pdf.table([patient_headers] + patient_data, width: 550, cell_style: { borders: [], padding: [4, 2] })
          end

          pdf.start_new_page if index < hospitals.size - 1
        end
      end

      threads << Thread.new do
        mutex.synchronize do
          send_file tempfile.path, filename: filename, type: "application/pdf"
        end
      end

      threads.each(&:join)
    end
  end

  def download_pdf_with_id
    mutex = Mutex.new
    threads = []
    
    hospital = Hospital.find(params[:id])
    filename = "#{hospital.name}_and_patients.pdf".gsub(' ', '_')
    
    threads << Thread.new do
      Prawn::Document.generate(filename) do |pdf|
        pdf.font_families.update("Georgia" => {
          normal: "#{Rails.root}/app/assets/fonts/NotoSansGeorgian-Regular.ttf",
          bold: "#{Rails.root}/app/assets/fonts/NotoSansGeorgian-Bold.ttf"
        })
        pdf.font "Georgia"
    
        pdf.move_down(10)
        pdf.text "Hospital Information", size: 14, style: :bold, align: :center
    
        hospital_data = [
          [{ content: 'Info', font_style: :bold }, { content: '', image: "#{Rails.root}/app/assets/images/hospital_info.png", fit: [20, 20] }],
          ["Hospital name", hospital.name],
          ["Email", hospital.email],
          ["Phone", hospital.phone],
          ["Address", hospital.address],
          ["Establishment Year", hospital.year],
          ["Type", hospital.facility],
          ["City", hospital.city],
          ["Mort. Rating", hospital.rating],
          ["Number of departments", hospital.departments.count],
          ["Number of doctors", hospital.doctors.count]
        ]
    
        pdf.table(hospital_data, width: 400, cell_style: { borders: [], padding: [4, 2] })
    
        if hospital.patients.any?
          pdf.move_down(10)
          pdf.text "Patients", size: 14, style: :bold, align: :center
    
          patient_headers = [
            { content: "Info", width: 43 },
            { content: "Name", width: 94 },
            { content: "Birth", width: 50 },
            { content: "Phone", width: 69 },
            { content: "Address", width: 119 },
            { content: "Code", width: 63 },

app/helpers/hospitals_helper.rb
module HospitalsHelper
  def calculate_age(birthdate)
    now = Time.now.utc.to_date
    age = now.year - birthdate.year
    age -= 1 if now.month < birthdate.month || (now.month == birthdate.month && now.day < birthdate.day)
    age
  end
end

app/views/hospitals/edit.html.erb
<%= stylesheet_link_tag 'form' %>

<h1> Update Hospital </h1>

<%= form_for @hospital, data: { turbo: false } do |f| %>
  <div>
    <%= f.label :name, class: "label" %>
    <%= f.text_field :name, class: "input-field inline", placeholder: "Hospital name" %><br>
  </div>

  <div>
    <%= f.label :email, class: "label" %>
    <%= f.text_field :email, class: "input-field inline", placeholder: "example@gmail.com" %><br>
  </div>
  
  <div>
    <%= f.label :phone, class: "label" %>
    <%= f.text_field :phone, class: "input-field inline", placeholder: "+3807654321" %><br>
  </div>
  
  <div>
    <%= f.label :address, class: "label" %>
    <%= f.text_field :address, class: "input-field inline", placeholder: "123 Adr Street" %><br>
  </div>

  <div>
    <%= f.label :year, class: "label" %>
    <%= f.text_field :year, class: "input-field inline", placeholder: "1700-2023" %><br>
  </div>

  <div>
    <%= f.label :facility, class: "label" %>
    <%= f.text_field :facility, class: "input-field inline", placeholder: "Hospital type" %><br>
  </div>

  <div>
    <%= f.label :city, class: "label" %>
    <%= f.text_field :city, class: "input-field inline", placeholder: "c. Avdeevka" %><br>
  </div>

  <div>
    <%= f.label :rating, class: "label" %>
    <%= f.text_field :rating, class: "input-field inline", placeholder: "Rate this!" %><br>
  </div>
  <%= f.submit "Update", class: "button" %><br>

  <div id="error-message" class="large-label"></div>
<% end %>

app/views/hospitals/index.html.erb
<%= stylesheet_link_tag 'view' %>

<h1> View Hospitals </h1>

<table>
  <thead>
    <tr>
      <th style="width: 55px;">
        <%= label_tag "id", "ID" %>
        <%= link_to params[:sort] == "id" && params[:direction] == "asc" ? "▼" : "▲", { sort: "id", direction: (params[:sort] == "id" && params[:direction] == "asc") ? "desc" : "asc", name: params[:name], departments_count: params[:departments_count], doctors_count: params[:doctors_count] }, class: "sort-icon #{params[:sort] == "id" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
      </th>
      <th style="width: 220px;">
        <%= form_tag(hospitals_search_path, method: "get") do %>
          <%= label_tag "name", "Name" %>
          <%= text_field_tag "name", params[:name], placeholder: "Search...", size: 4 %>
          <%= submit_tag "Search", class: "small-button" %>
          <%= link_to params[:sort] == "name" && params[:direction] == "asc" ? "▼" : "▲", { sort: "name", direction: (params[:sort] == "name" && params[:direction] == "asc") ? "desc" : "asc", name: params[:name], departments_count: params[:departments_count], doctors_count: params[:doctors_count] }, class: "sort-icon #{params[:sort] == "name" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>

        <% end %>
      </th>
      <th style="min-width: 120px; width: auto;">
        <%= label_tag "departments_count", "Number of departments" %>
        <%= link_to params[:sort] == "departments_count" && params[:direction] == "asc" ? "▼" : "▲", { sort: "departments_count", direction: (params[:sort] == "departments_count" && params[:direction] == "asc") ? "desc" : "asc", name: params[:name], departments_count: params[:departments_count], doctors_count: params[:doctors_count] }, class: "sort-icon #{params[:sort] == "departments_count" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
      </th>
      <th style="min-width: 120px; width: auto;">
        <%= label_tag "doctors_count", "Number of doctors" %>
        <%= link_to params[:sort] == "doctors_count" && params[:direction] == "asc" ? "▼" : "▲", { sort: "doctors_count", direction: (params[:sort] == "doctors_count" && params[:direction] == "asc") ? "desc" : "asc", name: params[:name], departments_count: params[:departments_count], doctors_count: params[:doctors_count] }, class: "sort-icon #{params[:sort] == "doctors_count" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
      </th>
      <th style="width: 120px;">
        <%= label_tag "facility", "Hospital Type" %>
        <%= link_to params[:sort] == "facility" && params[:direction] == "asc" ? "▼" : "▲", { sort: "facility", direction: (params[:sort] == "facility" && params[:direction] == "asc") ? "desc" : "asc", name: params[:name], departments_count: params[:departments_count], doctors_count: params[:doctors_count], facility: params[:facility], city: params[:city], rating: params[:rating] }, class: "sort-icon #{params[:sort] == "facility" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
      </th>
      <th style="width: 105px;">
        <%= label_tag "city", "City" %>
        <%= link_to params[:sort] == "city" && params[:direction] == "asc" ? "▼" : "▲", { sort: "city", direction: (params[:sort] == "city" && params[:direction] == "asc") ? "desc" : "asc", name: params[:name], departments_count: params[:departments_count], doctors_count: params[:doctors_count], facility: params[:facility], city: params[:city], rating: params[:rating] }, class: "sort-icon #{params[:sort] == "city" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
      </th>
      <th style="width: 120px;">
        <%= label_tag "rating", "Mortality rating" %>
        <%= link_to params[:sort] == "rating" && params[:direction] == "asc" ? "▼" : "▲", { sort: "rating", direction: (params[:sort] == "rating" && params[:direction] == "asc") ? "desc" : "asc", name: params[:name], departments_count: params[:departments_count], doctors_count: params[:doctors_count], facility: params[:facility], city: params[:city], rating: params[:rating] }, class: "sort-icon #{params[:sort] == "rating" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
      </th>
      <th colspan="3" style="width: 270px;">Do something?</th>
    </tr>
  </thead>
  <tbody>
    <% @hospitals.each do |hospital| %>
      <tr>
        <td><%= hospital.id %></td>
        <td><%= hospital.name %></td>
        <td><%= hospital.departments.count %></td>
        <td><%= hospital.doctors.count %></td>
        <td><%= hospital.facility %></td>
        <td><%= hospital.city %></td>
        <td><%= hospital.rating %></td>
        <td><%= link_to 'Show', hospital_path(hospital), class: "button" %></td>
        <td><%= link_to 'Edit', edit_hospital_path(hospital), class: "button" %></td>
        <td><%= button_to 'Delete', hospital_path(hospital), method: :delete, data: { confirm: 'Are you sure?' }, class: "button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @hospitals %>

<div class="links-container">
  <%= link_to 'Hospitals and patients (CSV)', hospitals_download_csv_path, class: "bottom-button" %>
  <%= link_to 'Hospitals and patients (PDF)', hospitals_download_pdf_path, class: "bottom-button" %>
  <%= link_to 'New Hospital', new_hospital_path, class: "bottom-button" %>
  <%= link_to 'Main page', '/', class: "bottom-button" %>
</div>

app/views/hospitals/new.html.erb
<%= stylesheet_link_tag 'form' %>

<h1> Add Hospital </h1>

<%= form_for @hospital do |f| %>
  <%= f.label :name, class: "label" %>
  <%= f.text_field :name, class: "input-field", placeholder: "Hospital name" %><br>

  <%= f.label :email, class: "label" %>
  <%= f.text_field :email, class: "input-field", placeholder: "example@gmail.com" %><br>

  <%= f.label :phone, class: "label" %>
  <%= f.text_field :phone, class: "input-field", placeholder: "+3807654321" %><br>

  <%= f.label :address, class: "label" %>
  <%= f.text_field :address, class: "input-field", placeholder: "123 Adr Street" %><br>

  <%= f.label :year, class: "label" %>
  <%= f.text_field :year, class: "input-field", placeholder: "1700-2023" %><br>
  <%= f.label :facility, class: "label" %>
  
  <%= f.text_field :facility, class: "input-field", placeholder: "Hospital type" %><br>

  <%= f.label :city, class: "label" %>
  <%= f.text_field :city, class: "input-field", placeholder: "c. Avdeevka" %><br>

  <%= f.label :rating, class: "label" %>
  <%= f.text_field :rating, class: "input-field", placeholder: "Rate this!" %><br>

  <%= f.submit "Create", class: "button" %>

  <div id="error-message" class="large-label"></div>
<% end %>

app/views/hospitals/show.html.erb
<%= stylesheet_link_tag 'view' %>

<h1> View Some Hospital </h1>

<table>
  <thead>
    <tr>
      <th style="width: 120px;">
        <%= label_tag "id", "Patient ID" %>
        <%= link_to params[:sort] == "id" && params[:direction] == "asc" ? "▼" : "▲", { sort: "id", direction: (params[:sort] == "id" && params[:direction] == "asc") ? "desc" : "asc" }, class: "sort-icon #{params[:sort] == "id" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
      </th>
      <th style="width: 220px;">
        <%= form_tag(hospitals_search_show_path(@hospital.id), method: "get") do %>
          <%= label_tag "name", "Name" %>
          <%= text_field_tag "name", params[:name], placeholder: "Search...", size: 4 %>
          <%= submit_tag "Search", class: "small-button" %>
          <%= link_to params[:sort] == "name" && params[:direction] == "asc" ? "▼" : "▲", { sort: "name", direction: (params[:sort] == "name" && params[:direction] == "asc") ? "desc" : "asc" }, class: "sort-icon #{params[:sort] == "name" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
        <% end %>
      </th>
      <th style="width: 280px;">
        <%= form_tag(hospitals_search_show_path(@hospital.id), method: "get") do %>
          <%= label_tag "age", "Patient Age" %>
          <%= text_field_tag "age", params[:age], placeholder: "Search...", size: 4 %>
          <%= submit_tag "Search", class: "small-button" %>
          <%= link_to params[:sort] == "birthdate" && params[:direction] == "asc" ? "▼" : "▲", { sort: "birthdate", direction: (params[:sort] == "birthdate" && params[:direction] == "asc") ? "desc" : "asc" }, class: "sort-icon #{params[:sort] == "birthdate" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
        <% end %>
      </th>
      <th style="width: 90px;">
        <%= label_tag "card_code", "Card Code" %>
      </th>
      <th style="width: 240px;">
        <%= form_tag(hospitals_search_show_path(@hospital.id), method: "get") do %>
          <%= label_tag "phone", "Phone" %>
          <%= text_field_tag "phone", params[:phone], placeholder: "Search...", size: 4 %>
          <%= submit_tag "Search", class: "small-button" %>
          <%= link_to params[:sort] == "phone" && params[:direction] == "asc" ? "▼" : "▲", { sort: "phone", direction: (params[:sort] == "phone" && params[:direction] == "asc") ? "desc" : "asc" }, class: "sort-icon #{params[:sort] == "phone" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
        <% end %>
      </th>
      <th colspan="2">Do something?</th>
    </tr>
  </thead>
  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.id %></td>
        <td><%= patient.name %></td>
        <td><%= calculate_age(patient.birthdate) %></td>
        <td><%= @patientcards[patient.id].code %></td>
        <td><%= patient.phone %></td>
        <td>
          <%= link_to Doctor.find_by(id: @patientcards[patient.id]&.doctor_id)&.name, doctor_path(@patientcards[patient.id]&.doctor_id), class: "button" if @patientcards[patient.id] %>
        </td>
        <td><%= link_to "Show", patient_path(patient), class: "button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @patients %>

<div class="links-container">
  <%= link_to 'Hospital info (PDF)', hospitals_download_pdf_with_id_path, class: "bottom-button" %>
  <%= link_to 'Back to hospitals', hospitals_path, class: "bottom-button" %>
  <%= link_to 'Main page', '/', class: "bottom-button" %>
</div>