config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'mainpage#index'

  get 'hospitals/search', to: 'hospitals#search', as: 'hospitals_search'
  get 'hospitals/download_csv', to: 'hospitals#download_csv', as: 'hospitals_download_csv'
  get 'hospitals/download_pdf', to: 'hospitals#download_pdf', as: 'hospitals_download_pdf'
  get 'hospitals/:id/download_pdf/', to: 'hospitals#download_pdf_with_id', as: 'hospitals_download_pdf_with_id'
  get 'users/download_pdf/', to: 'mainpage#download_pdf', as: 'users_download_pdf'
  get 'hospitals/:id/searchshow', to: 'hospitals#searchshow', as: 'hospitals_search_show'
  get 'departments/search', to: 'departments#search', as: 'departments_search'
  get 'doctors/search', to: 'doctors#search', as: 'doctors_search'
  get 'specialties/search', to: 'specialties#search', as: 'specialties_search'
  get 'patient_cards/search', to: 'patient_cards#search', as: 'patient_cards_search'
  get 'patients/search', to: 'patients#search', as: 'patients_search'

  root 'mainpage#index'

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :hospitals do
    resources :departments
  end

  resources :departments do
    resources :doctors
  end

  resources :departments do
    resources :patient_cards
  end

  resources :patient_cards

  resources :patients

  resources :doctors do
    resources :specialties
  end

  resources :specialties
end

app/controllers/mainpage_controller.rb
require "thread"

class MainpageController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end

  def download_pdf
    mutex = Mutex.new
    threads = []

    filename = "users.pdf"

    threads << Thread.new do
      Prawn::Document.generate(filename) do |pdf|
        pdf.font_families.update("Georgia" => {
          normal: Rails.root.join("app", "assets", "fonts", "NotoSansGeorgian-Regular.ttf"),
          bold: Rails.root.join("app", "assets", "fonts", "NotoSansGeorgian-Bold.ttf")
        })
        pdf.font("Georgia")

        pdf.move_down(10)
        pdf.text("Users Information", size: 14, style: :bold, align: :center)

        table_headers = [
          { content: "Info", width: 30 },
          { content: "Email", width: 170 },
          { content: "Encrypted password", width: 250 },
          { content: "Creation date", width: 100 }
        ]
        users = User.all
        users_data = users.map do |user|
          created_at = user.created_at.strftime('%Y-%m-%d')
          pass = user == current_user ? user.encrypted_password : "Private info"
          [
            { content: '', image: Rails.root.join("app", "assets", "images", "user_info.png"), fit: [20, 20] },
            user.email,
            pass,
            created_at[0, 10]
          ]
        end
        pdf.table([table_headers] + users_data, width: 550, cell_style: { borders: [], padding: [4, 2] })
      end

      mutex.synchronize do
        send_file(filename, filename: filename, type: "application/pdf")
      end
    end

    threads.each(&:join)
  end
end

app/helpers/mainpage_helper.rb
module MainpageHelper
end

app/views/mainpage/index.html.erb
<%= stylesheet_link_tag 'main' %>

<h1>Hospital app</h1>
<div class="links-container">
  <%= link_to 'View hospitals', hospitals_path, class: "button" %>
  <%= link_to 'View departments', departments_path, class: "button" %>
  <%= link_to 'View doctors', doctors_path, class: "button" %>
  <%= link_to 'View specialties', specialties_path, class: "button" %>
  <%= link_to 'View patients', patients_path, class: "button" %>
  <%= link_to 'View patient cards', patient_cards_path, class: "button" %>

  <% if user_signed_in? %>
    <% @user = current_user %>
      <div class="user-info">
        <% if @user.avatar.attached? %>
          <%= image_tag url_for(@user.avatar), alt: "Icon1", width: 50, height: 50 %>
        <% else %>
          <%= image_tag asset_path('user_info.png'), alt: "Icon2", width: 50, height: 50 %>
        <% end %>
        <p>Logged in as <%= current_user.email %></p>
      </div>
    <%= button_to 'Users private info (PDF)', users_download_pdf_path, class: "button" %>
    <%= button_to "Edit account", edit_user_registration_path(current_user), method: :get, class: "button" %>
    <%= form_tag destroy_user_session_path, method: :delete do %>
      <%= submit_tag "Log out", class: "button" %>
    <% end %>
    <%= form_for(current_user, url: registration_path(current_user), html: { method: :delete }) do |f| %>
      <%= f.submit "Delete account", class: "button" %>
    <% end %>
  <% else %>
    <%= link_to "Sign in", '/users/sign_in', class: "button" %>
  <% end %>
</div>