config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'mainpage#index'

  get 'hospitals/search', to: 'hospitals#search', as: 'hospitals_search'
  get 'hospitals/download_csv', to: 'hospitals#download_csv', as: 'hospitals_download_csv'
  get 'hospitals/download_pdf', to: 'hospitals#download_pdf', as: 'hospitals_download_pdf'
  get 'hospitals/:id/download_pdf/', to: 'hospitals#download_pdf_with_id', as: 'hospitals_download_pdf_with_id'
  get 'users/download_pdf/', to: 'mainpage#download_pdf', as: 'users_download_pdf'
  get 'hospitals/:id/searchshow', to: 'hospitals#searchshow', as: 'hospitals_search_show'
  get 'departments/search', to: 'departments#search', as: 'departments_search'
  get 'doctors/search', to: 'doctors#search', as: 'doctors_search'
  get 'specialties/search', to: 'specialties#search', as: 'specialties_search'
  get 'patient_cards/search', to: 'patient_cards#search', as: 'patient_cards_search'
  get 'patients/search', to: 'patients#search', as: 'patients_search'

  root 'mainpage#index'

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :hospitals do
    resources :departments
  end

  resources :departments do
    resources :doctors
  end

  resources :departments do
    resources :patient_cards
  end

  resources :patient_cards

  resources :patients

  resources :doctors do
    resources :specialties
  end

  resources :specialties
end

app/models/doctor.rb
class Doctor < ApplicationRecord
	belongs_to :department
	belongs_to :specialty
	has_many :patient_cards, dependent: :destroy

	validates :name, presence: true, length: { maximum: 255 }
	validates :email, presence: true, length: { maximum: 255 }, format: { with: URI::MailTo::EMAIL_REGEXP, message: "Invalid email format!" }
	validates :phone, presence: true, length: { maximum: 20 }, format: { with: /\A\+?\d+\z/, message: "Invalid phone format!" }

	def update_name(new_name)
		self.name = new_name
		save
	end

	def update_email(new_email)
		self.email = new_email
		save
	end

	def update_phone(new_phone)
		self.phone = new_phone
		save
	end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

  def index
    @doctors = DoctorQuery.new(Doctor.page(params[:page]).per(10))
    @doctors = @doctors.sort(params[:sort], params[:direction]) if params[:sort].present?
    @doctors = @doctors.search(:name, params[:name]) if params[:name].present?
    @doctors = @doctors.result
  end
  
  def search
    @doctors = DoctorQuery.new(Doctor.page(params[:page]).per(10))
    @doctors = @doctors.sort(params[:sort], params[:direction]) if params[:sort].present?
    @doctors = @doctors.search(:name, params[:name]) if params[:name].present?
    @doctors = @doctors.result

    render :index
  end

  def show
    @doctor = Doctor.find(params[:id])
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)

    if @doctor.save
      redirect_to doctor_path(@doctor)
    else
      render :new
    end
  end

  def edit
    @doctor = Doctor.find(params[:id])
  end

  def update
    @doctor = Doctor.find(params[:id])

    if @doctor.update(doctor_params)
      redirect_to doctor_path(@doctor)
    else
      puts @doctor.errors.full_messages
      render :edit
    end
  end

  def destroy
    @doctor = Doctor.find(params[:id])
    @doctor.destroy
    redirect_to doctors_path
  end

  private

  def doctor_params
    params.require(:doctor).permit(:name, :email, :phone, :specialty_id, :department_id)
  end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/edit.html.erb
<%= stylesheet_link_tag 'form' %>

<h1> Update Doctor </h1>

<%= form_for @doctor do |f| %>
  <%= f.label :name, class: "label" %>
  <%= f.text_field :name, class: "input-field", placeholder: "Test Testov Testovich" %><br>

  <%= f.label :email, class: "label" %>
  <%= f.text_field :email, class: "input-field", placeholder: "Doc's email" %><br>

  <%= f.label :phone, class: "label" %>
  <%= f.text_field :phone, class: "input-field", placeholder: "+3807654321" %><br>

  <%= f.label :department_id, class: "label" %>
  <%= f.number_field :department_id, class: "input-field", placeholder: "Department ID" %><br>

  <%= f.label :specialty_id, class: "label" %>
  <%= f.number_field :specialty_id, class: "input-field", placeholder: "Specialty ID" %><br>

  <%= f.submit "Update", class: "button" %>

  <div id="error-message" class="large-label"></div>
<% end %>

app/views/doctors/index.html.erb
<%= stylesheet_link_tag 'view' %>

<h1>View doctors</h1>

<table>
  <thead>
    <tr>
      <th style="width: 55px;">
        <%= label_tag "id", "ID" %>
        <%= link_to params[:sort] == "id" && params[:direction] == "asc" ? "▼" : "▲", { sort: "id", direction: params[:sort] == "id" && params[:direction] == "asc" ? "desc" : "asc", id: params[:id] }, class: "sort-icon #{params[:sort] == "id" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
      </th>
      <th style="width: 220px;">
        <%= form_tag(doctors_search_path, method: "get") do %>
          <%= label_tag "name", "Name" %>
          <%= text_field_tag "name", params[:name], placeholder: "Search...", size: 4 %>
          <%= submit_tag "Search", class: "small-button" %>
          <%= link_to params[:sort] == "name" && params[:direction] == "asc" ? "▼" : "▲", { sort: "name", direction: params[:sort] == "name" && params[:direction] == "asc" ? "desc" : "asc", name: params[:name] }, class: "sort-icon #{params[:sort] == "name" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
        <% end %>
      </th>
      <th style="width: 125px;">
        <%= label_tag "email", "Email" %>
        <%= link_to params[:sort] == "email" && params[:direction] == "asc" ? "▼" : "▲", { sort: "email", direction: params[:sort] == "email" && params[:direction] == "asc" ? "desc" : "asc", email: params[:email] }, class: "sort-icon #{params[:sort] == "email" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
      </th>
      <th style="width: 135px">
        <%= label_tag "phone", "Phone" %>
        <%= link_to params[:sort] == "phone" && params[:direction] == "asc" ? "▼" : "▲", { sort: "phone", direction: params[:sort] == "phone" && params[:direction] == "asc" ? "desc" : "asc", phone: params[:phone] }, class: "sort-icon #{params[:sort] == "phone" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
      </th>
      <th style="width: 150px;">
        <%= label_tag "department_id", "Department ID" %>
        <%= link_to params[:sort] == "department_id" && params[:direction] == "asc" ? "▼" : "▲", { sort: "department_id", direction: params[:sort] == "department_id" && params[:direction] == "asc" ? "desc" : "asc", department_id: params[:department_id] }, class: "sort-icon #{params[:sort] == "department_id" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
      </th>
      <th style="width: 135px;">
        <%= label_tag "specialty_id", "Specialty ID" %>
        <%= link_to params[:sort] == "specialty_id" && params[:direction] == "asc" ? "▼" : "▲", { sort: "specialty_id", direction: params[:sort] == "specialty_id" && params[:direction] == "asc" ? "desc" : "asc", specialty_id: params[:specialty_id] }, class: "sort-icon #{params[:sort] == "specialty_id" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
      </th>
      <th colspan="3" style="width: 270px;">Do something?</th>
    </tr>
  </thead>
  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.id %></td>
        <td><%= doctor.name %></td>
        <td><%= doctor.email %></td>
        <td><%= doctor.phone %></td>
        <td><%= doctor.department_id %></td>
        <td><%= doctor.specialty_id %></td>
        <td><%= link_to 'Show', doctor_path(doctor), class: "button" %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor), class: "button" %></td>
        <td><%= button_to 'Delete', doctor_path(doctor), method: :delete, data: { confirm: 'Are you sure?' }, class: "button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @doctors %>

<div class="links-container">
  <%= link_to 'New Doctor', new_doctor_path, class: "bottom-button" %>
  <%= link_to 'Main page', '/', class: "bottom-button" %>
</div>

app/views/doctors/new.html.erb
<%= stylesheet_link_tag 'form' %>

<h1> Add Doctor </h1>

<%= form_for @doctor do |f| %>
  <%= f.label :name, class: "label" %>
  <%= f.text_field :name, class: "input-field", placeholder: "Test Testov Testovich" %><br>

  <%= f.label :email, class: "label" %>
  <%= f.text_field :email, class: "input-field", placeholder: "example@gmail.com" %><br>

  <%= f.label :phone, class: "label" %>
  <%= f.text_field :phone, class: "input-field", placeholder: "+3807654321" %><br>

  <%= f.label :department_id, class: "label" %>
  <%= f.number_field :department_id, class: "input-field", placeholder: "Department ID" %><br>
  
  <%= f.label :specialty_id, class: "label" %>
  <%= f.number_field :specialty_id, class: "input-field", placeholder: "Specialty ID" %><br>


  <%= f.submit "Create", class: "button" %>

  <div id="error-message" class="large-label"></div>
<% end %>

app/views/doctors/show.html.erb
<%= stylesheet_link_tag 'view' %>

<h1> View Some Doctor </h1>

<table>
  <tr>
    <td> ID: </td>
    <td> <%= @doctor.id %> </td>
  </tr>

  <tr>
    <td> Name: </td>
    <td> <%= @doctor.name %> </td>
  </tr>

  <tr>
    <td> Email: </td>
    <td> <%= @doctor.email %> </td>
  </tr>

  <tr>
    <td> Phone: </td>
    <td> <%= @doctor.phone %> </td>
  </tr>

  <tr>
    <td> Department ID: </td>
    <td> <%= @doctor.department_id %> </td>
  </tr>

  <tr>
    <td> Specialty ID: </td>
    <td> <%= @doctor.specialty_id %> </td>
  </tr>

</table>

<div class="links-container">
  <%= link_to 'Update', edit_doctor_path(@doctor), class: "bottom-button" %>
  <%= link_to 'Back to doctors', doctors_path, class: "bottom-button" %>
  <%= link_to 'Back to hospitals', hospitals_path, class: "bottom-button" %>
</div>